Добавлены новые эндпоинты
potokk/public-api pull request #22
Opened 2022-12-05 12:50 UTC by SaetovDaniil

Анкета сб, команда по вакансии, отклик, приоритеты

2022-12-05 13:14 UTC, VakhitovaIrina requested changes

2022-12-05 13:14 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +          description: Не найдена вакансия или кандидата
кандидат

2022-12-06 12:02 UTC, VakhitovaIrina requested changes

2022-12-06 12:02 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +      description: Позволяет обновить информацию кандидату на вакансии об отклике с работного сайта
информацию по кандидату на вакансии

2022-12-06 12:02 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +      description: 'Позволяет получить информацию о всех приоритетах компании для потребностей '
обо всех

2022-12-06 12:02 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +          description: Название словаря со значениями приоритетов (всегда '
кажется, здесь чего-то не хватает

2022-12-06 12:02 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +      description: Возвращает ID и имя анкеты СБ. Используется если есть несколько форм анкеты СБ и заполнение происходит во внешней системе. Позволяет внешней системе понимать какую форму анкеты СБ
запятые потерялись

Используется, если есть несколько форм анкеты СБ и заполнение происходит во внешней системе. Позволяет внешней системе понимать, какую форму анкеты СБ отображать кандидату в интерфейсе.

2022-12-06 12:05 UTC, VakhitovaIrina approved these changes

2022-12-06 12:06 UTC, VakhitovaIrina approved these changes

2022-12-06 13:28 UTC, you11neverknow approved these changes

2022-12-06 13:29 UTC, merged

2022-12-06 14:45 UTC, you11neverknow reviewed
стили!