Добавлены новые эндпоинты (обновление)
potokk/public-api pull request #23
Opened 2022-12-19 14:01 UTC by SaetovDaniil

2022-12-19 14:38 UTC, VakhitovaIrina requested changes

2022-12-19 14:38 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +                    subject: Встреча с канидадатов
Встреча с кандидатом

2022-12-19 14:38 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +                    subject: Встреча с канидадатов
Встреча с кандидатом

2022-12-19 14:38 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +          subject: Встреча с канидадатов
Встреча с кандидатом

2022-12-19 14:38 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +          example: Встреча с канидадатов
Встреча с кандидатом

2022-12-20 09:50 UTC, VakhitovaIrina approved these changes

2022-12-26 14:22 UTC, you11neverknow approved these changes

2022-12-26 14:23 UTC, merged