Ptk 16543 - внесение обновление и добавление новых эндпоинтов
potokk/public-api pull request #25
Opened 2023-01-12 17:04 UTC by SaetovDaniil

2023-01-13 06:35 UTC, VakhitovaIrina requested changes

2023-01-13 06:35 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +      description: Данный метод позволяет отобрать уже созданного кандидата на вакансию
заменить _отобрать_ на _добавить_

2023-01-13 06:40 UTC, VakhitovaIrina approved these changes

2023-01-13 06:41 UTC, VakhitovaIrina approved these changes

2023-01-18 14:14 UTC, you11neverknow approved these changes

2023-01-18 14:14 UTC, merged

2023-01-18 14:23 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +            Для `Пример ответа 3` - если переданный в запросе кандидат уже отобран на переданную в запросе вакансию, то возвращается ошибка, что такая связь кандидат-вакансия уже есть в системе, в то
лишние запятые:
уже есть в системе, в том числе если кандидат `Отклонен` или был деперсонализован

2023-01-18 14:23 UTC, VakhitovaIrina commented on potok-api-v3.yaml
> +                    subject: Встреча с канидадатом
опечатка