Добавлен эндпоинт для назначения ответственного рекрутера по вакансии
potokk/public-api pull request #44
Opened 2024-10-22 11:52 UTC by e-shyndeeva

Добавлен эндпоинт для назначения ответственного рекрутера по вакансии

2025-02-11 07:55 UTC, TeperikDmitry requested changes, later dismissed
Оставил 2 комментария. Просьба поправить.

2025-02-11 07:55 UTC, TeperikDmitry commented on potok-api-v3.yaml
> +                user_email:
на user_email - ругается.
Кажется, что тут парамеnр называется "email"

2025-02-11 07:55 UTC, TeperikDmitry commented on potok-api-v3.yaml
> +      description: 'Данный метод позволяет назначить пользователя ответственным рекрутером по вакансии. Важно: пользователь уже должен состоять в команде по вакансии.'
Лучше убрать словосочетание "Данный метод" для поддержания единообразия описания.

2025-11-25 08:43 UTC, CheranevaDi approved these changes
ОК

2025-11-25 08:47 UTC, merged